---
all:
  children:
    headnode:
      hosts:
        bmaas-prod-head:
          ansible_host: "{{ bcm_head_ssh_ip }}"
          ansible_user: root
    compute:
      vars:
        ansible_user: root
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      children:
        b200_nodes:
          hosts: "{{ b200_host_map | default({}) }}"
