//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hand (controller-gen equivalent). DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Activation) DeepCopyInto(out *Activation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Activation.
func (in *Activation) DeepCopy() *Activation {
	if in == nil {
		return nil
	}
	out := new(Activation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignedLabel) DeepCopyInto(out *AssignedLabel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignedLabel.
func (in *AssignedLabel) DeepCopy() *AssignedLabel {
	if in == nil {
		return nil
	}
	out := new(AssignedLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompletionStatus) DeepCopyInto(out *CompletionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompletionStatus.
func (in *CompletionStatus) DeepCopy() *CompletionStatus {
	if in == nil {
		return nil
	}
	out := new(CompletionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRef) DeepCopyInto(out *NodeRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRef.
func (in *NodeRef) DeepCopy() *NodeRef {
	if in == nil {
		return nil
	}
	out := new(NodeRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadinessStatus) DeepCopyInto(out *ReadinessStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadinessStatus.
func (in *ReadinessStatus) DeepCopy() *ReadinessStatus {
	if in == nil {
		return nil
	}
	out := new(ReadinessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantNodeAssignment) DeepCopyInto(out *TenantNodeAssignment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantNodeAssignment.
func (in *TenantNodeAssignment) DeepCopy() *TenantNodeAssignment {
	if in == nil {
		return nil
	}
	out := new(TenantNodeAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantNodeAssignment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantNodeAssignmentList) DeepCopyInto(out *TenantNodeAssignmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenantNodeAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantNodeAssignmentList.
func (in *TenantNodeAssignmentList) DeepCopy() *TenantNodeAssignmentList {
	if in == nil {
		return nil
	}
	out := new(TenantNodeAssignmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantNodeAssignmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantNodeAssignmentSpec) DeepCopyInto(out *TenantNodeAssignmentSpec) {
	*out = *in
	out.TenantRef = in.TenantRef
	out.NodeRef = in.NodeRef
	out.Activation = in.Activation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantNodeAssignmentSpec.
func (in *TenantNodeAssignmentSpec) DeepCopy() *TenantNodeAssignmentSpec {
	if in == nil {
		return nil
	}
	out := new(TenantNodeAssignmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantNodeAssignmentStatus) DeepCopyInto(out *TenantNodeAssignmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.AssignedLabel = in.AssignedLabel
	out.Completion = in.Completion
	out.Readiness = in.Readiness
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantNodeAssignmentStatus.
func (in *TenantNodeAssignmentStatus) DeepCopy() *TenantNodeAssignmentStatus {
	if in == nil {
		return nil
	}
	out := new(TenantNodeAssignmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantRef) DeepCopyInto(out *TenantRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantRef.
func (in *TenantRef) DeepCopy() *TenantRef {
	if in == nil {
		return nil
	}
	out := new(TenantRef)
	in.DeepCopyInto(out)
	return out
}
