---
all:
  children:
    headnode:
      hosts:
        az2-stg-head:
          ansible_host: "{{ bcm_head_ssh_ip }}"
          ansible_user: root
    compute:
      vars:
        ansible_user: root
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      children:
        gpu_nodes:
          hosts:
            stg-gpu-001:
              ansible_host: 10.10.100.10
        cpu_nodes:
          hosts:
            stg-cpu-001:
              ansible_host: 10.10.100.1
            stg-cpu-002:
              ansible_host: 10.10.100.2
            stg-cpu-003:
              ansible_host: 10.10.100.3
