apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-node-assignment-operator
  namespace: argocd
spec:
  project: compute-platform
  source:
    repoURL: https://github.com/compute-platform/tenant-node-assignment-operator.git
    path: charts/tenant-node-assignment-operator
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: compute-platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
