apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: compute-platform
  namespace: argocd
spec:
  description: Compute Platform operators and infrastructure
  sourceRepos:
    - https://github.com/compute-platform/*
  destinations:
    - namespace: compute-platform-system
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
