apiVersion: nlm.cic.io/v1
kind: NodeState
metadata:
  name: cpu-kr1a-001
  labels: {}
  updated_at: '2026-03-14T09:06:17.363029+00:00'
  updated_by: nlm-maintenance
spec:
  desired_state: repair
  tenant: ''
