apiVersion: nlm.cic.io/v1
kind: NodeState
metadata:
  name: gpu-h200-001
  labels: {}
  updated_at: '2026-03-14T09:06:17.129342+00:00'
  updated_by: nlm-controller
spec:
  desired_state: testing
  tenant: ''
