apiVersion: nlm.cic.io/v1
kind: NodeState
metadata:
  name: gpu-dev-005
  labels: {}
  updated_at: '2026-03-14T08:40:32.293497+00:00'
  updated_by: nlm-maintenance
spec:
  desired_state: repair
  tenant: ''
